/** Background resource work remains manager-owned across Remote and Loader lifetimes. */
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { describe, expect, it, onTestFinished, vi } from 'vitest'
import type { SecurityResourceAvailability, SecuritySkillResourceStatus } from '../src/types.ts'
import { resourceHarness } from './resources-harness.ts'

function installed(value: SecurityResourceAvailability): asserts value is SecuritySkillResourceStatus {
  expect(value.state).toBe('installed')
  if (value.state === 'unavailable') throw new Error('Resource manager missing')
  expect(value.installed).toBeDefined()
}

describe('Host-owned security resource operations through Remotes', () => {
  it('continues a download after its observer disconnects and exposes committed registry state', async () => {
    const b = await resourceHarness()
    expect(await b.ctx.skills.snapshot()).toMatchObject({ skills: [] })
    b.holdArchive()
    const listeners = b.ctx.events._hooks['security-skill-resources/changed']?.length ?? 0
    const observer = new AbortController()
    onTestFinished(() => { observer.abort() })
    const stream = await b.ctx.typertGateway.wireStream.open('securityResearch/observeResources', { args: {} }, observer.signal)
    const iterator = stream[Symbol.asyncIterator]()
    expect((await iterator.next()).value).toMatchObject({ state: 'not-installed' })
    const caller = new AbortController()
    const started = await b.call('installResource', undefined, caller.signal)
    caller.abort(new Error('initiating client disconnected'))
    expect(started.operation).toMatchObject({ kind: 'install' })
    await vi.waitFor(() => { expect(b.pendingRequests()).toBe(1) })
    observer.abort()
    await iterator.return?.()
    expect(b.ctx.events._hooks['security-skill-resources/changed'] ?? []).toHaveLength(listeners)
    expect((await b.call('describeResources')).operation?.id).toBe(started.operation?.id)
    b.releaseArchive()
    const complete = await b.settled()
    installed(complete)
    expect(complete.installed?.source.kind).toBe('download')
    expect(complete.lastError).toBeUndefined()
    expect(JSON.parse(await readFile(join(b.resources, 'active.json'), 'utf8')))
      .toMatchObject({ installed: { generation: complete.installed?.generation } })
    await vi.waitFor(async () => {
      expect((await b.ctx.skills.snapshot()).skills.map(skill => skill.name)).toContain('resource-fixture')
    })
    const loaded = await b.ctx.skills.get('resource-fixture')
    expect(loaded?.content).toBe('FIRST_RESOURCE')
    expect(loaded?.resourceBase?.kind).toBe('directory')
    if (loaded?.resourceBase?.kind !== 'directory') throw new Error('Loaded resource has no directory')
    const retainedSkill = join(loaded.resourceBase.path, 'SKILL.md')
    await b.call('removeResource')
    expect(await b.settled()).toMatchObject({ state: 'not-installed' })
    await vi.waitFor(async () => { expect((await b.ctx.skills.snapshot()).skills).toEqual([]) })
    expect(await readFile(retainedSkill, 'utf8')).toContain('FIRST_RESOURCE')
    await b.assertNoStaging()
  })

  it('cancels only an observed operation and preserves the committed generation on failure', async () => {
    const b = await resourceHarness()
    await b.call('installResource')
    const first = await b.settled()
    installed(first)
    const generation = first.installed!.generation
    await expect(b.call('installResource'))
      .rejects.toMatchObject({ code: 'security-research/resource-request-failed', details: { code: 'already-installed' } })
    await b.release('SECOND_RESOURCE')
    b.holdArchive()
    const active = await b.call('updateResource')
    await vi.waitFor(() => { expect(b.pendingRequests()).toBe(1) })
    await expect(b.call('reinstallResource'))
      .rejects.toMatchObject({ code: 'security-research/resource-request-failed', details: { code: 'busy' } })
    const cancelled = await b.call('cancelResource', { operationId: active.operation!.id })
    expect(cancelled.operation).toBeUndefined()
    expect(cancelled.installed?.generation).toBe(generation)
    await b.assertNoStaging()
    const replacement = await b.call('updateResource')
    await vi.waitFor(() => { expect(b.pendingRequests()).toBe(1) })
    expect(replacement.operation!.id).not.toBe(active.operation!.id)
    await expect(b.call('cancelResource', { operationId: active.operation!.id }))
      .rejects.toMatchObject({ code: 'security-research/resource-request-failed', details: { code: 'stale-operation' } })
    expect((await b.call('describeResources')).operation?.id).toBe(replacement.operation!.id)
    await b.call('cancelResource', { operationId: replacement.operation!.id })
    b.releaseArchive()
    b.corruptArchive()
    await b.call('reinstallResource')
    const failed = await b.settled()
    expect(failed).toMatchObject({ state: 'installed', installed: { generation } })
    expect(failed.lastError).toBeTruthy()
    expect(JSON.parse(await readFile(join(b.resources, 'active.json'), 'utf8'))).toMatchObject({ installed: { generation } })
    await b.assertNoStaging()
    await b.call('removeResource')
    expect(await b.settled()).toMatchObject({ state: 'not-installed' })
  })

  it('retains background work through controller reload and stops it when its manager unloads', async () => {
    const b = await resourceHarness()
    b.holdArchive()
    const started = await b.call('installResource')
    await vi.waitFor(() => { expect(b.pendingRequests()).toBe(1) })
    const oldController = b.ctx.securityResearchController
    const observer = oldController.observeResources(new AbortController().signal)[Symbol.asyncIterator]()
    await observer.next()
    const next = observer.next()
    await b.enabled('controller', false)
    expect(await next).toEqual({ done: true, value: undefined })
    expect((await b.ctx.securitySkillResources.status()).operation?.id).toBe(started.operation!.id)
    await b.enabled('controller', true)
    expect(b.ctx.securityResearchController).not.toBe(oldController)
    expect((await b.call('describeResources')).operation?.id).toBe(started.operation!.id)
    await b.enabled('provider', false)
    await b.enabled('manager', false)
    await vi.waitFor(() => { expect(b.pendingRequests()).toBe(0) })
    expect(await b.call('describeResources')).toEqual({ state: 'unavailable', reason: 'component-missing' })
    await b.assertNoStaging()
    await b.enabled('manager', true)
    expect(await b.call('describeResources')).toMatchObject({ state: 'not-installed' })
    expect(b.archiveRequests()).toBe(1)
  })

  it('installs bundled resources only through the explicit Remote action without a release endpoint', async () => {
    const b = await resourceHarness(false)
    expect((await b.ctx.skills.snapshot()).skills).toEqual([])
    expect((await b.call('installBundledResource')).operation?.kind).toBe('install-bundled')
    // The bundled corpus copies real reviewed files; its I/O exceeds the tiny HTTP fixture budget.
    const complete = await b.settled(10000)
    expect(complete).toMatchObject({ state: 'installed', installed: { source: { kind: 'bundled' } } })
    expect(complete.lastError).toBeUndefined()
    await vi.waitFor(async () => { expect((await b.ctx.skills.snapshot()).skills.length).toBe(complete.installed!.skillCount) })
    expect(b.archiveRequests()).toBe(0)
    await b.assertNoStaging()
  })

  it('checks releases without downloading and keeps absent download configuration explicit', async () => {
    const b = await resourceHarness()
    expect((await b.call('checkResourceUpdate')).operation?.kind).toBe('check-update')
    const checked = await b.settled()
    expect(checked.state).toBe('not-installed')
    expect(checked.available?.bytes).toBeGreaterThan(0)
    expect(b.archiveRequests()).toBe(0)
    await expect(b.call('updateResource'))
      .rejects.toMatchObject({ code: 'security-research/resource-request-failed', details: { code: 'not-installed' } })
    const unconfigured = await resourceHarness(false)
    const unconfiguredStatus = await unconfigured.call('describeResources')
    expect(unconfiguredStatus.download.available).toBe(false)
    expect(typeof unconfiguredStatus.download.reason).toBe('string')
    await expect(unconfigured.call('installResource'))
      .rejects.toMatchObject({ code: 'security-research/resource-request-failed', details: { code: 'not-configured' } })
    expect(unconfigured.archiveRequests()).toBe(0)
  })
})
